In [17]:
# Importar librer√≠as necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv("/content/Mexico_50_Columnas.csv", on_bad_lines='skip', quoting=1, encoding='utf-8')
df

,review_scores_accuracy,review_scores_location,host_total_listings_count,instant_bookable,number_of_reviews,latitude,property_type,longitude,room_type,availability_60,...,review_scores_checkin,availability_365,host_verifications,last_review,number_of_reviews_ltm,host_location,price,review_scores_value,amenities,calculated_host_listings_count
0,NaN,NaN,1,f,0,19.383820,Entire villa,-99.273340,Entire home/apt,58,...,NaN,363,"['email', 'phone', 'work_email']",NaN,0,"Mexico City, Mexico","$3,865.00",NaN,"[""Free parking on premises"", ""Washer"", ""Wifi"",...",1
1,4.56,4.98,13,f,64,19.411620,Entire home,-99.177940,Entire home/apt,24,...,4.87,325,"['email', 'phone', 'work_email']",2023-03-26,0,"Mexico City, Mexico",NaN,4.48,"[""Iron"", ""Washer"", ""Wifi"", ""Host greets you"", ...",8
2,4.81,4.98,4,f,49,19.411520,Entire rental unit,-99.168570,Entire home/apt,20,...,4.94,325,"['email', 'phone']",2024-05-05,4,"Mexico City, Mexico","$2,029.00",4.91,"[""Iron"", ""Wifi"", ""Bathtub"", ""Refrigerator"", ""D...",2
3,4.90,4.96,4,f,127,19.356140,Entire rental unit,-99.163080,Entire home/apt,27,...,4.96,257,"['email', 'phone', 'work_email']",2024-09-22,7,"Mexico City, Mexico","$1,140.00",4.92,"[""Iron"", ""Washer"", ""Outdoor furniture"", ""Wifi""...",3
4,5.00,4.91,7,f,11,19.432110,Entire loft,-99.193270,Entire home/apt,9,...,5.00,275,"['email', 'phone']",2023-08-16,0,"Mexico City, Mexico","$3,633.00",4.82,"[""Iron"", ""Washer"", ""Outdoor furniture"", ""Wifi""...",3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26577,NaN,NaN,279,t,0,19.387329,Private room in guesthouse,-99.246731,Private room,60,...,NaN,365,"['email', 'phone']",NaN,0,"Mexico City, Mexico",$488.00,NaN,"[""Wifi"", ""Heating"", ""Freezer"", ""Cleaning avail...",37
26578,NaN,NaN,16,t,0,19.432687,Room in hotel,-99.197736,Private room,0,...,NaN,177,"['email', 'phone']",NaN,0,"Mexico City, Mexico","$2,800.00",NaN,"[""Shared patio or balcony"", ""Iron"", ""Outdoor f...",16
26579,NaN,NaN,16,t,0,19.432687,Room in hotel,-99.197736,Private room,0,...,NaN,177,"['email', 'phone']",NaN,0,"Mexico City, Mexico","$2,700.00",NaN,"[""Shared patio or balcony"", ""Iron"", ""Outdoor f...",16
26580,NaN,NaN,16,t,0,19.432687,Room in hotel,-99.197736,Private room,0,...,NaN,177,"['email', 'phone']",NaN,0,"Mexico City, Mexico","$2,600.00",NaN,"[""Shared patio or balcony"", ""Iron"", ""Outdoor f...",16
26581,NaN,NaN,6,t,0,19.443476,Entire rental unit,-99.201748,Entire home/apt,48,...,NaN,150,"['email', 'phone']",NaN,0,"Mexico City, Mexico","$1,353.00",NaN,"[""Free parking on premises"", ""Washer"", ""TV"", ""...",4

In [19]:
# Mostrar primeras filas del dataset
df.head()

,review_scores_accuracy,review_scores_location,host_total_listings_count,instant_bookable,number_of_reviews,latitude,property_type,longitude,room_type,availability_60,...,review_scores_checkin,availability_365,host_verifications,last_review,number_of_reviews_ltm,host_location,price,review_scores_value,amenities,calculated_host_listings_count
0,NaN,NaN,1,f,0,19.38382,Entire villa,-99.27334,Entire home/apt,58,...,NaN,363,"['email', 'phone', 'work_email']",NaN,0,"Mexico City, Mexico","$3,865.00",NaN,"[""Free parking on premises"", ""Washer"", ""Wifi"",...",1
1,4.56,4.98,13,f,64,19.41162,Entire home,-99.17794,Entire home/apt,24,...,4.87,325,"['email', 'phone', 'work_email']",2023-03-26,0,"Mexico City, Mexico",NaN,4.48,"[""Iron"", ""Washer"", ""Wifi"", ""Host greets you"", ...",8
2,4.81,4.98,4,f,49,19.41152,Entire rental unit,-99.16857,Entire home/apt,20,...,4.94,325,"['email', 'phone']",2024-05-05,4,"Mexico City, Mexico","$2,029.00",4.91,"[""Iron"", ""Wifi"", ""Bathtub"", ""Refrigerator"", ""D...",2
3,4.90,4.96,4,f,127,19.35614,Entire rental unit,-99.16308,Entire home/apt,27,...,4.96,257,"['email', 'phone', 'work_email']",2024-09-22,7,"Mexico City, Mexico","$1,140.00",4.92,"[""Iron"", ""Washer"", ""Outdoor furniture"", ""Wifi""...",3
4,5.00,4.91,7,f,11,19.43211,Entire loft,-99.19327,Entire home/apt,9,...,5.00,275,"['email', 'phone']",2023-08-16,0,"Mexico City, Mexico","$3,633.00",4.82,"[""Iron"", ""Washer"", ""Outdoor furniture"", ""Wifi""...",3

In [20]:
# Identificar valores nulos por columna
valores_nulos = df.isnull().sum()
print("Valores nulos por columna:")
print(valores_nulos)

Valores nulos por columna:
review_scores_accuracy                           3657
review_scores_location                           3657
host_total_listings_count                           0
instant_bookable                                    0
number_of_reviews                                   0
latitude                                            0
property_type                                       0
longitude                                           0
room_type                                           0
availability_60                                     0
host_is_superhost                                1509
availability_30                                     0
bedrooms                                          866
calculated_host_listings_count_entire_homes         0
bathrooms_text                                     26
accommodates                                        0
calculated_host_listings_count_private_rooms        0
host_response_time                               3622
description                                       933
host_name                                           0
minimum_nights                                      0
neighbourhood_group_cleansed                    26582
neighborhood_overview                           10895
neighbourhood                                   10895
number_of_reviews_l30d                              0
availability_90                                     0
host_acceptance_rate                             2869
first_review                                     3656
name                                                0
beds                                             2953
host_identity_verified                              0
review_scores_rating                             3656
host_neighbourhood                              12915
maximum_nights                                      0
host_response_rate                               3622
review_scores_cleanliness                        3657
neighbourhood_cleansed                              0
has_availability                                 1008
review_scores_communication                      3657
host_listings_count                                 0
review_scores_checkin                            3657
availability_365                                    0
host_verifications                                  0
last_review                                      3656
number_of_reviews_ltm                               0
host_location                                    5441
price                                            2927
review_scores_value                              3657
amenities                                           0
calculated_host_listings_count                      0
dtype: int64

In [21]:
# M√©todo de imputaci√≥n de valores nulos
df.fillna(df.mean(numeric_only=True), inplace=True)

In [22]:
# Para valores categ√≥ricos, reemplazar nulos con la moda usando mapeo de diccionario
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [25]:
# Manejo de valores nulos en la columna 'neighbourhood_group_cleansed'
if df['neighbourhood_group_cleansed'].isnull().sum() > 0:
    df['neighbourhood_group_cleansed'].fillna("Indefinido", inplace=True)

<ipython-input-25-bc9f9d621ec2>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['neighbourhood_group_cleansed'].fillna("Indefinido", inplace=True)
<ipython-input-25-bc9f9d621ec2>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Indefinido' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['neighbourhood_group_cleansed'].fillna("Indefinido", inplace=True)

In [26]:
# Verificar que no queden valores nulos
print("Valores nulos despu√©s de la imputaci√≥n:")
print(df.isnull().sum())

Valores nulos despu√©s de la imputaci√≥n:
review_scores_accuracy                          0
review_scores_location                          0
host_total_listings_count                       0
instant_bookable                                0
number_of_reviews                               0
latitude                                        0
property_type                                   0
longitude                                       0
room_type                                       0
availability_60                                 0
host_is_superhost                               0
availability_30                                 0
bedrooms                                        0
calculated_host_listings_count_entire_homes     0
bathrooms_text                                  0
accommodates                                    0
calculated_host_listings_count_private_rooms    0
host_response_time                              0
description                                     0
host_name                                       0
minimum_nights                                  0
neighbourhood_group_cleansed                    0
neighborhood_overview                           0
neighbourhood                                   0
number_of_reviews_l30d                          0
availability_90                                 0
host_acceptance_rate                            0
first_review                                    0
name                                            0
beds                                            0
host_identity_verified                          0
review_scores_rating                            0
host_neighbourhood                              0
maximum_nights                                  0
host_response_rate                              0
review_scores_cleanliness                       0
neighbourhood_cleansed                          0
has_availability                                0
review_scores_communication                     0
host_listings_count                             0
review_scores_checkin                           0
availability_365                                0
host_verifications                              0
last_review                                     0
number_of_reviews_ltm                           0
host_location                                   0
price                                           0
review_scores_value                             0
amenities                                       0
calculated_host_listings_count                  0
dtype: int64

In [27]:
# Guardar el dataset limpio
df.to_csv('Mexico_Limpio_SinNulos.csv')